import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/Components/Navbar";
import Footer from "@/app/Components/Footer";
import BookAppointment from "./contexts/BookAppointment";

const poppins = Poppins({ 
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
});

export const metadata = {
  title: "Tuckshop App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className} >
        <BookAppointment>
          <div className="bg-neutral-50 w-full overflow-hidden">
            <Navbar />
            <main>{children}</main>
            <Footer />
          </div>
        </BookAppointment>
      </body>
    </html>
  );
}
